// <auto-generated />
namespace Ruby.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class thumb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(thumb));
        
        string IMigrationMetadata.Id
        {
            get { return "201810030650574_thumb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
