// <auto-generated />
namespace Ruby.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class users_discount : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(users_discount));
        
        string IMigrationMetadata.Id
        {
            get { return "201810150836418_users_discount"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
