// <auto-generated />
namespace Ruby.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class product_type_image2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(product_type_image2));
        
        string IMigrationMetadata.Id
        {
            get { return "201808261426007_product_type_image2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
